#!/bin/python3
import os, sys
from bs4 import BeautifulSoup
import fitz
import json
import re

def resize_paper(paper_id):
    doc = fitz.open(f"raw/{paper_id}.pdf")
    papersize = ""
    if doc[0].rect.x1 > doc[0].rect.y1:
        papersize = '{297mm,210mm}' # a4 paper in landscape
    else:
        papersize = '{210mm,297mm}' # a4 paper in portrait
    os.system(f"pdfjam --papersize {papersize} raw/{paper_id}.pdf --outfile raw/{paper_id}.pdf")

def parse_paper(paper):
    pdf_path = f"raw/{paper}.pdf"
    output_path = f"artifact/{paper}"
    os.system(f"time ./parse {pdf_path} {output_path}")

def custom_int(s):
    if s[-4:] == ".txt":
        s = s[:-4]
    try:
        return int(s)
    except:
        return 0

def concat_text(paper):
    path = f"artifact/{paper}/text"
    content = ""
    for file in sorted(os.listdir(path), key=custom_int):
        if file == "." or file == "..": continue
        content += open(f"{path}/{file}", "r").read()
    with open(f"artifact/{paper}/merged.txt", "w") as f:
        f.write(content)

def convert_question(paper_path, content):
    content = content.prettify().replace("<div>", "").replace("</div>", "")
    content = content.replace("\n", "").strip()
    content = content.replace("<u> ", "<u>").replace("<u> ", "<u>").replace(" </u>", "</u>") # prettify add spaces?
    content = re.sub("^\\d+\\.", "", content)
    content = content.replace("figures/", f"artifact/{paper_path}/figure/")
    content = content.replace("<br>", "<br/>")
    lines = [_.strip() for _ in content.split("<br/>") if len(_.strip()) > 0]
    statement, options = [], []
    for line in lines:
        if re.match(r"[A-E]\.", line):
            line = line[2:].strip()
            options.append(line)
        else:
            statement.append(line)
    statement = "<br/>".join(statement)
    return {
        'statement': statement,
        'options': options
    }

def convert_html_to_json(paper_path):
    content = open(f"artifact/{paper_path}/questions.html").read()
    soup = BeautifulSoup(content, "html.parser")
    questions = []
    for question in soup.find_all("div"):
        questions.append(convert_question(paper_path, question))
    with open(f"artifact/{paper_path}/questions.json", "w") as f:
        f.write(json.dumps(questions))
    print(f"Written output to artifact/{paper_path}/questions.json.")

def gen_figure(paper_path):
    cmd = f"./gen_figure raw/{paper_path}.pdf artifact/{paper_path}/figures.json artifact/{paper_path}/figure"
    os.system(cmd)

def fix_formatting(paper_path):
    file_path = f"artifact/{paper_path}/questions.html"
    os.system(f"python3 fix_formatting.py {file_path} {file_path}")

# year = 2006
# for year in range(1999, 2001):
# paperID = f"paper-2/{year}"
# resize_paper(paperID)
# parse_paper(paperID)
#     concat_text(paperID)

if len(sys.argv) >= 2:
    paperID = f"paper-2/{sys.argv[1]}"
    if "--fix" in sys.argv:
        print("Fixing Formatting...")
        fix_formatting(paperID)
    convert_html_to_json(paperID)
    gen_figure(paperID)
