[MISSING_PAGE_EMPTY:1]

[MISSING_PAGE_EMPTY:2]

[MISSING_PAGE_EMPTY:3]

[MISSING_PAGE_EMPTY:4]

[MISSING_PAGE_EMPTY:5]

[MISSING_PAGE_FAIL:6]

The figure shows the triangle \(WXY\). Let \(Z\) be a point lying on \(WY\) such that \(WY:XY=XY:YZ\). If \(WX=65\) cm, \(WZ=25\) cm and \(XZ=60\) cm, then \(XY=\) A. 131 cm. B. 144 cm. C. 156 cm. D. 169 cm.

19. In the figure, \(ABCD\) is a square. Let \(E\) be a point such that \(CDEF\) is a rhombus, where \(F\) is a point lying on \(AC\) produced. \(DF\) is produced to the point \(G\) such that \(AF/I\)\(BG\). Which of the following are true? 

20. It is given that \(PQRS\) is a trapezium with \(PQ//SR\). If \(PS=41\) cm, \(RS=53\) cm, \(\angle PSR=120^{\circ}\) and \(\angle QRS=150^{\circ}\), then \(PQ=\) A. 82 cm. B. 100 cm. C. 106 cm. D. 135 cm.

21. In the figure, \(ABCD\) is a rectangle. It is given that \(AE=20\) cm and \(\angle AED=90^{\circ}\). If the area of \(\Delta ADE\) is \(150\) cm\({}^{2}\), then the perpendicular distance from \(E\) to \(CD\) is A. \(8\) cm. B. \(9\) cm. C. \(12\) cm. D. \(15\) cm.
22. In the figure, \(RSTUV\) is a circle. It is given that \(RT//\,VU\) and \(RT\) is the angle bisector of \(\angle SRU\). If \(\angle RTS=\angle URV=33^{\circ}\), then \(\angle RUT=\) A. \(36^{\circ}\). B. \(49^{\circ}\). C. \(65^{\circ}\). D. \(71^{\circ}\).
23. The figure shows the quadrilateral \(ABCD\). If \(\angle ABC+\angle ADC=\angle ACD=\angle BAC=90^{\circ}\), which of the following must be true? A. \(\tan\angle ACB=\frac{AB}{AD}\) B. \(\tan\angle ACB=\frac{AB}{CD}\) C. \(\tan\angle ADC=\frac{BC}{AD}\) D. \(\tan\angle ADC=\frac{BC}{CD}\)The polar coordinates of the points \(X\), \(Y\) and \(Z\) are \((1,20^{\circ})\), \((2,80^{\circ})\) and \((r,\theta)\) respectively, where \(20^{\circ}<\theta<80^{\circ}\). If \(\Delta XYZ\) is an equilateral triangle, find \(r\).

A. \(\sqrt{3}\)

B. \(\sqrt{5}\)

C. \(\sqrt{7}\)

D. \(\sqrt{10}\)

25. Denote the origin by \(O\). The coordinates of the point \(A\) are \((a,2a)\), where \(a>0\). Let \(P\) be a moving point in the rectangular coordinate plane such that \(AP=OA\). The locus of \(P\) is a

A. point.

B. circle.

C. rhombus.

D. straight line.

26. The straight lines \(L_{1}\) and \(L_{2}\) are perpendicular to each other. The equations of \(L_{1}\) and \(L_{2}\) are \(3x+4y-20=0\) and \(mx+ny-20=0\) respectively, where \(m\) and \(n\) are constants. Suppose that \(L_{1}\) and \(L_{2}\) cut the \(x\)-axis at the points \(A\) and \(B\) respectively. Let \(C\) be the point of intersection of \(L_{1}\) and \(L_{2}\). It is given that \(C\) lies above the \(x\)-axis. If the area of \(\Delta ABC\) is \(6\), find \(n\).

A. \(-12\)

B. \(-9\)

C. \(9\)

D. \(12\)

27. The coordinates of the centre of the circle \(C\) are \((7,-5)\). If \(C\) cuts the \(x\)-axis at the points \(P\) and \(Q\) such that \(PQ=24\), then the equation of \(C\) is

A. \(x^{2}+y^{2}-14x+10y-95=0\).

B. \(x^{2}+y^{2}+14x-10y-95=0\).

C. \(x^{2}+y^{2}-14x+10y-119=0\).

D. \(x^{2}+y^{2}+14x-10y-119=0\).

[MISSING_PAGE_FAIL:10]

[MISSING_PAGE_EMPTY:11]

[MISSING_PAGE_EMPTY:12]

[MISSING_PAGE_EMPTY:13]

[MISSING_PAGE_FAIL:14]

[MISSING_PAGE_FAIL:15]