It is given that \(z\) varies directly as the cube of \(x\) and inversely as the square of \(y\). When \(x=3\) and \(y=6\), \(z=3\). When \(x=5\) and \(y=2\), \(z=\) A. \(5\). B. \(25\). C. \(125\). D. \(243\).

Let \(a_{n}\) be the \(n\)th term of a sequence. If \(a_{2}=3\), \(a_{5}=41\) and \(a_{n+2}=2a_{n+1}+a_{n}\) for any positive integer \(n\), then \(a_{6}=\) A. \(99\). B. \(101\). C. \(239\). D. \(243\).

In the figure, the equation of the straight line \(L\) is \(px+qy=7\). Which of the following is/are true?

[MISSING_PAGE_POST]

I. \(p>7\) III. \(q>p\) A.

15. The perimeter of the sector \(OMN\) is \(12\pi\) cm, where \(O\) is the centre of the sector \(OMN\). If the radius of the sector \(OMN\) is \(3\pi\) cm, which of the following are true? 1. The area of the sector \(OMN\) is \(9\pi^{2}\) cm\({}^{2}\). 2. The perimeter of \(\Delta OMN\) is less than \(35\) cm. 3. The angle of the sector \(OMN\) is greater than \(100^{\circ}\). 1. 1.

The figure shows the triangle \(WXY\). Let \(Z\) be a point lying on \(WY\) such that \(WY:XY=XY:YZ\). If \(WX=65\) cm, \(WZ=25\) cm and \(XZ=60\) cm, then \(XY=\) A. 131 cm. B. 144 cm. C. 156 cm. D. 169 cm.

19. In the figure, \(ABCD\) is a square. Let \(E\) be a point such that \(CDEF\) is a rhombus, where \(F\) is a point lying on \(AC\) produced. \(DF\) is produced to the point \(G\) such that \(AF/I\)\(BG\). Which of the following are true? 

20. It is given that \(PQRS\) is a trapezium with \(PQ//SR\). If \(PS=41\) cm, \(RS=53\) cm, \(\angle PSR=120^{\circ}\) and \(\angle QRS=150^{\circ}\), then \(PQ=\) A. 82 cm. B. 100 cm. C. 106 cm. D. 135 cm.

21. In the figure, \(ABCD\) is a rectangle. It is given that \(AE=20\) cm and \(\angle AED=90^{\circ}\). If the area of \(\Delta ADE\) is \(150\) cm\({}^{2}\), then the perpendicular distance from \(E\) to \(CD\) is A. \(8\) cm. B. \(9\) cm. C. \(12\) cm. D. \(15\) cm.
22. In the figure, \(RSTUV\) is a circle. It is given that \(RT//\,VU\) and \(RT\) is the angle bisector of \(\angle SRU\). If \(\angle RTS=\angle URV=33^{\circ}\), then \(\angle RUT=\) A. \(36^{\circ}\). B. \(49^{\circ}\). C. \(65^{\circ}\). D. \(71^{\circ}\).
23. The figure shows the quadrilateral \(ABCD\). If \(\angle ABC+\angle ADC=\angle ACD=\angle BAC=90^{\circ}\), which of the following must be true? A. \(\tan\angle ACB=\frac{AB}{AD}\) B. \(\tan\angle ACB=\frac{AB}{CD}\) C. \(\tan\angle ADC=\frac{BC}{AD}\) D. \(\tan\angle ADC=\frac{BC}{CD}\)